name: Run tests

on:
  push:
    branches:
      - main
      - "*.x"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and update Python dependencies
        run: python -m pip install --upgrade pip build
      - name: Build
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)
          pyproject-build . --sdist --wheel
          cd dist && sha256sum * | tee SHA256SUMS
      - name: Upload builds
        uses: actions/upload-artifact@v2
        with:
          name: pep440 dist ${{ github.run_number }}
          path: ./dist

  lint:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and update Python dependencies
        run: python -m pip install --upgrade pip build
      - name: Download builds
        uses: actions/download-artifact@v2
        with:
          name: pep440 dist ${{ github.run_number }}
          path: ./dist
      - name: Install lint dependencies
        run: python -m pip install .[lint]
      - name: Check builds
        run: check-manifest
      - name: Type check with mypy
        run: mypy --strict pep440

  test:
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.10", "pypy-3.8"]
        include:
          - os: ubuntu-latest
            python-version: "3.11-dev"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and update Python dependencies
        run: python -m pip install --upgrade pip
      - name: Install package and test dependencies
        run: python -m pip install -e .[test]
      - name: pytest
        run: |
          pytest --cov=pep440 --cov-branch --cov-report=xml --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=100
